version: "3.9"

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
      args:
        PYTHON_VERSION: 3.12-slim
    container_name: av_mcp_server
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      DB_HOST: pgvector
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword
      COLLECTION_NAME: product_embeddings
      DB_URL: postgresql+psycopg://appuser:apppassword@pgvector:5432/appdb
      INIT_DB: "1"   # после первоначальной загрузки поменяй на "0"
    ports:
      - "8001:8001"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"         # откроется на http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin-data: